name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting deployment..."

            if [ ! -d "movie_recommender_deployed_aws" ]; then
              git clone https://github.com/119-sam/movie_recommender_deployed_aws.git
            fi

            cd movie_recommender_deployed_aws

            git pull

            sudo docker stop movie-recommender || true
            sudo docker rm movie-recommender || true

            sudo docker build -t movie-recommender .
            sudo docker run -d -p 8501:8501 --name movie-recommender movie-recommender